name: Java CI with Maven and Node.js

on:
  push:
    branches: [ "master", "feature/spring" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install frontend dependencies
      run: pnpm install
      working-directory: ./frontend/

    - name: Build frontend
      run: pnpm build
      working-directory: ./frontend/

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build backend
      run: mvn -B package --file ./pom.xml
      working-directory: ./backend-spring/dreamed-house/

  release:
    runs-on: ubuntu-latest

    needs: build  # Ensure that the 'build' job is completed before starting this job

    steps:
      # - name: Set up Git
      #   run: |
      #     git config --global user.email "you@example.com"
      #     git config --global user.name "Your Name"

      # - name: Create Release Tag
      #   run: |
      #     git tag -a v1.0.0 -m "Release version 1.0.0"
      #     git push origin v1.0.0

      - name: Upload JAR to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./backend-spring/dreamed-house/target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}